# Generated by Django 5.0.1 on 2024-01-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderd_item',
            old_name='product',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='orderd_item',
            old_name='quantitt',
            new_name='quantity',
        ),
    ]
